#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "$ROOT_DIR"

mapfile -t STAGED_FILES < <(git diff --cached --name-only --diff-filter=ACMR)

if [ ${#STAGED_FILES[@]} -eq 0 ]; then
  echo "No staged files to review."
  exit 0
fi

echo "Reviewing staged files for secrets and obvious risks..."

blocked=0
waned=0

block_file() {
  local file="$1"
  echo "BLOCKED: staged file should not be committed: $file"
  blocked=1
}

wan_match() {
  local file="$1"
  local message="$2"
  echo "WARNING: $file -> $message"
  waned=1
}

is_binary_staged_file() {
  local file="$1"
  git diff --cached --numstat -- "$file" | grep -Eq '^-[[:space:]]+-[[:space:]]+'
}

for file in "${STAGED_FILES[@]}"; do
  case "$file" in
    .env.example|.env.*.example)
      ;;
    .env|.env.*|*.pem|*.key|*.p12|*.kdbx|erl_crash.dump)
      block_file "$file"
      ;;
  esac
done

if ! git diff --cached --check -- .; then
  echo "BLOCKED: staged diff contains conflict markers or whitespace errors."
  blocked=1
fi

for file in "${STAGED_FILES[@]}"; do
  if ! git cat-file -e ":$file" 2>/dev/null; then
    continue
  fi

  if is_binary_staged_file "$file"; then
    continue
  fi

  if [ "$file" = "scripts/review-staged.sh" ]; then
    continue
  fi

  if git show ":$file" | grep -Eq "BEGIN PRIVATE KEY|BEGIN RSA PRIVATE KEY|BEGIN OPENSSH PRIVATE KEY"; then
    echo "BLOCKED: private key material detected in $file"
    blocked=1
  fi

  if git show ":$file" \
    | grep -Eiv '^[[:space:]]*#' \
    | grep -Ev '[:=][[:space:]]*["'"'"']?(<[^>]+>|\$\{[^}]+\})["'"'"']?([[:space:]]*\\)?$' \
    | grep -Eq "(^|[^A-Z])(SECRET_KEY_BASE|DB_ENCRYPTION_KEY|SONAR_TOKEN|API_KEY|ACCESS_TOKEN|AUTH_TOKEN|AWS_SECRET_ACCESS_KEY)[[:space:]]*[:=][[:space:]]*[^[:space:]][^[:space:]]*"; then
    echo "BLOCKED: likely secret value detected in $file"
    blocked=1
  fi

  if git show ":$file" | grep -Eq "TODO|FIXME|XXX"; then
    wan_match "$file" "contains TODO/FIXME/XXX markers"
  fi

  if git show ":$file" | grep -Eq "Generated by create next app|This is a \\[Next\\.js\\] project bootstrapped"; then
    wan_match "$file" "contains default generated boilerplate text"
  fi
done

if [ "$blocked" -ne 0 ]; then
  echo "Commit blocked by staged review."
  exit 1
fi

if [ "$waned" -ne 0 ]; then
  echo "Staged review completed with wanings."
else
  echo "Staged review passed."
fi